### ISSUE TITLE
TODO: Set up the server-side fields validation process.

### ISSUE THREAD

**Issue by CprojectsDev** [cprojectsorg/Qatdatabase#29]
https://github.com/cprojectsorg/Qatdatabase/commit/feca9730704f2c1199267537872d0e2a67eb363b#diff-e12cb8291bb9ad61ec681a9998f77606R311

**Comment by TheNextStage** [comment]
https://github.com/cprojectsorg/Qatdatabase/commit/994e8adf4110ef6a156bc5833416e303c777481e
